! GMANPRE - Version 6.83 (last changed 1996/08/08 22:33:39)
 file nlrflap.cgd
 units fss
 ZONE 1
   BOUNDARY OLAP
     CUTTER SURFACE TYPE
    CUTTER SURFACE NEW
    CUTTER SURFACE IN ZONE 2  I17 J23 K1 TO I163 J23 K1 INCREMENT 1
    CUTTER SURFACE IN ZONE 2  I17 J1 K1 TO I17 J23 K1 INCREMENT 1
    CUTTER SURFACE IN ZONE 2  I163 J1 K1 TO I163 J23 K1 INCREMENT 1
 LABEL 10
    GENERATE HOLE
    FRINGE-MODE HOLE
    GENERATE FRINGE
    SET FRINGE BOUNDARY COUPLED TO ZONE 2 BOUNDARY OLAP
     UPDATE
 ZONE 2
   BOUNDARY OLAP
    FRINGE-MODE OUTER BOUNDARY  ON I1
    FRINGE-MODE OUTER BOUNDARY  ON IMAX
    FRINGE-MODE OUTER BOUNDARY  ON JMAX
 LABEL 11
    GENERATE FRINGE
    SET FRINGE BOUNDARY COUPLED TO ZONE 1 BOUNDARY OLAP
     UPDATE
 ZONE 1
   BOUNDARY I1
     CONFINED OUTFLOW
     UPDATE
   BOUNDARY IMAX
     CONFINED OUTFLOW
     UPDATE
   BOUNDARY J1
 SUBAREA I29 I177
     VISCOUS WALL
 SUBAREA I1 I29
     COUPLED TO ZONE 1 BOUNDARY J1
 SUBAREA I177 I205
     COUPLED TO ZONE 1 BOUNDARY J1
     UPDATE
   BOUNDARY JMAX
     INFLOW OUTFLOW
     UPDATE
 ZONE 2
   BOUNDARY J1
 SUBAREA I21 I159
     VISCOUS WALL
 SUBAREA I1 I21
     COUPLED TO ZONE 2 BOUNDARY J1
 SUBAREA I159 I179
     COUPLED TO ZONE 2 BOUNDARY J1
     UPDATE
